Rename Companion to BlueOS
bluerobotics/BlueOS-Water-Linked-DVL pull request #2
Opened 2022-02-08 04:15 UTC by ES-Alexander

Updates companion to BlueOS throughout the repository.

Requires updating the docker image name (I'm unsure if capitals are supported, so they'll need to be removed from the installation instructions in the README if they're not), and the repo should also be renamed.

Unrelated:
Fixes #1

2022-05-18 14:41 UTC, Williangalvani requested changes

2022-05-18 14:41 UTC, Williangalvani commented on README.md
> +`sudo docker run -d --net=host -v /root/.config/BlueOS:/root/.config --name=BlueOS-dvl-all-in-one --restart=unless-stopped williangalvani/BlueOS-dvl:all-in-one
we use lower case blueos for theconfig  path, can you update it?

2022-05-19 07:51 UTC, ES-Alexander commented on README.md
> +`sudo docker run -d --net=host -v /root/.config/BlueOS:/root/.config --name=BlueOS-dvl-all-in-one --restart=unless-stopped williangalvani/BlueOS-dvl:all-in-one
@Williangalvani Is that just the first one, or all three?

2022-05-19 21:11 UTC, Williangalvani commented on README.md
> +`sudo docker run -d --net=host -v /root/.config/BlueOS:/root/.config --name=BlueOS-dvl-all-in-one --restart=unless-stopped williangalvani/BlueOS-dvl:all-in-one
just the one in the path `/root/.config/blueos:/root/.config`

2022-05-20 03:16 UTC, Williangalvani approved these changes

2022-05-20 03:16 UTC, merged